"""
This type stub file was generated by pyright.
"""

from .mtprotoplainsender import MTProtoPlainSender
from .authenticator import do_authentication
from .mtprotosender import MTProtoSender
from .connection import Connection, ConnectionHttp, ConnectionTcpAbridged, ConnectionTcpFull, ConnectionTcpIntermediate, ConnectionTcpMTProxyAbridged, ConnectionTcpMTProxyIntermediate, ConnectionTcpMTProxyRandomizedIntermediate, ConnectionTcpObfuscated, TcpMTProxy

"""
This module contains several classes regarding network, low level connection
with Telegram's servers and the protocol used (TCP full, abridged, etc.).
"""
