"""
This type stub file was generated by pyright.
"""

from .connection import Connection, PacketCodec

SSL_PORT = ...
class HttpPacketCodec(PacketCodec):
    tag = ...
    obfuscate_tag = ...
    def encode_packet(self, data):
        ...
    
    async def read_packet(self, reader):
        ...
    


class ConnectionHttp(Connection):
    packet_codec = HttpPacketCodec
    async def connect(self, timeout=..., ssl=...): # -> None:
        ...
    


