"""
This type stub file was generated by pyright.
"""

from .connection import Connection, PacketCodec

class FullPacketCodec(PacketCodec):
    tag = ...
    def __init__(self, connection) -> None:
        ...
    
    def encode_packet(self, data):
        ...
    
    async def read_packet(self, reader):
        ...
    


class ConnectionTcpFull(Connection):
    """
    Default Telegram mode. Sends 12 additional bytes and
    needs to calculate the CRC value of the packet itself.
    """
    packet_codec = FullPacketCodec


