"""
This type stub file was generated by pyright.
"""

_sentinel = ...
class EntityCache:
    def __init__(self, hash_map: dict = ..., self_id: int = ..., self_bot: bool = ...) -> None:
        ...
    
    def set_self_user(self, id, bot, hash): # -> None:
        ...
    
    def get(self, id): # -> Entity | None:
        ...
    
    def extend(self, users, chats): # -> None:
        ...
    
    def get_all_entities(self): # -> list[Entity]:
        ...
    
    def put(self, entity): # -> None:
        ...
    
    def retain(self, filter): # -> None:
        ...
    
    def __len__(self): # -> int:
        ...
    


