"""
This type stub file was generated by pyright.
"""

from html.parser import HTMLParser
from typing import Iterable, List, Tuple
from ..tl.types import TypeMessageEntity

"""
Simple HTML -> Telegram entity parser.
"""
class HTMLToTelegramParser(HTMLParser):
    def __init__(self) -> None:
        ...
    
    def handle_starttag(self, tag, attrs): # -> None:
        ...
    
    def handle_data(self, text): # -> None:
        ...
    
    def handle_endtag(self, tag): # -> None:
        ...
    


def parse(html: str) -> Tuple[str, List[TypeMessageEntity]]:
    """
    Parses the given HTML message and returns its stripped representation
    plus a list of the MessageEntity's that were found.

    :param html: the message with HTML to be parsed.
    :return: a tuple consisting of (clean message, [message entities]).
    """
    ...

ENTITY_TO_FORMATTER = ...
def unparse(text: str, entities: Iterable[TypeMessageEntity]) -> str:
    """
    Performs the reverse operation to .parse(), effectively returning HTML
    given a normal text and its MessageEntity's.

    :param text: the text to be reconverted into HTML.
    :param entities: the MessageEntity's applied to the text.
    :return: a HTML representation of the combination of both inputs.
    """
    ...

