"""
This type stub file was generated by pyright.
"""

class ParticipantPermissions:
    """
    Participant permissions information.

    The properties in this objects are boolean values indicating whether the
    user has the permission or not.

    Example
        .. code-block:: python

            permissions = ...

            if permissions.is_banned:
                "this user is banned"
            elif permissions.is_admin:
                "this user is an administrator"
    """
    def __init__(self, participant, chat: bool) -> None:
        ...
    
    @property
    def is_admin(self): # -> bool:
        """
        Whether the user is an administrator of the chat or not. The creator
        also counts as begin an administrator, since they have all permissions.
        """
        ...
    
    @property
    def is_creator(self): # -> bool:
        """
        Whether the user is the creator of the chat or not.
        """
        ...
    
    @property
    def has_default_permissions(self): # -> bool:
        """
        Whether the user is a normal user of the chat (not administrator, but
        not banned either, and has no restrictions applied).
        """
        ...
    
    @property
    def is_banned(self): # -> bool:
        """
        Whether the user is banned in the chat.
        """
        ...
    
    @property
    def has_left(self): # -> bool:
        """
        Whether the user left the chat.
        """
        ...
    
    @property
    def add_admins(self): # -> bool:
        """
        Whether the administrator can add new administrators with the same or
        less permissions than them.
        """
        ...
    
    ban_users = ...
    pin_messages = ...
    invite_users = ...
    delete_messages = ...
    edit_messages = ...
    post_messages = ...
    change_info = ...
    anonymous = ...
    manage_call = ...


