"""
This type stub file was generated by pyright.
"""

from .. import TLObject

class GzipPacked(TLObject):
    CONSTRUCTOR_ID = ...
    def __init__(self, data) -> None:
        ...
    
    @staticmethod
    def gzip_if_smaller(content_related, data): # -> bytes:
        """Calls bytes(request), and based on a certain threshold,
           optionally gzips the resulting data. If the gzipped data is
           smaller than the original byte array, this is returned instead.

           Note that this only applies to content related requests.
        """
        ...
    
    def __bytes__(self): # -> bytes:
        ...
    
    @staticmethod
    def read(reader): # -> bytes:
        ...
    
    @classmethod
    def from_reader(cls, reader): # -> GzipPacked:
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    


