"""
This type stub file was generated by pyright.
"""

from .. import TLObject

class RpcResult(TLObject):
    CONSTRUCTOR_ID = ...
    def __init__(self, req_msg_id, body, error) -> None:
        ...
    
    @classmethod
    def from_reader(cls, reader): # -> RpcResult:
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    


