"""
This type stub file was generated by pyright.
"""

from .. import TLObject

class TLMessage(TLObject):
    """
    https://core.telegram.org/mtproto/service_messages#simple-container.

    Messages are what's ultimately sent to Telegram:
        message msg_id:long seqno:int bytes:int body:bytes = Message;

    Each message has its own unique identifier, and the body is simply
    the serialized request that should be executed on the server, or
    the response object from Telegram. Since the body is always a valid
    object, it makes sense to store the object and not the bytes to
    ease working with them.

    There is no need to add serializing logic here since that can be
    inlined and is unlikely to change. Thus these are only needed to
    encapsulate responses.
    """
    SIZE_OVERHEAD = ...
    def __init__(self, msg_id, seq_no, obj) -> None:
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    


