"""
This type stub file was generated by pyright.
"""

from ...tl.tlobject import TLRequest
from typing import TYPE_CHECKING
from ...tl.types import TypeInputCollectible

"""File generated by TLObjects' generator. All changes will be ERASED"""
if TYPE_CHECKING:
    ...
class GetCollectibleInfoRequest(TLRequest):
    CONSTRUCTOR_ID = ...
    SUBCLASS_OF_ID = ...
    def __init__(self, collectible: TypeInputCollectible) -> None:
        """
        :returns fragment.CollectibleInfo: Instance of CollectibleInfo.
        """
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    
    @classmethod
    def from_reader(cls, reader): # -> Self:
        ...
    


