"""
This type stub file was generated by pyright.
"""

import re
from .common import AlreadyInConversationError, AuthKeyNotFound, BadMessageError, CdnFileTamperedError, InvalidBufferError, InvalidChecksumError, MultiError, ReadCancelledError, SecurityError, TypeNotFoundError
from .rpcbaseerrors import *
from .rpcerrorlist import *

"""
This module holds all the base and automatically generated errors that the
Telegram API has. See telethon_generator/errors.json for more.
"""
def rpc_message_to_error(rpc_error, request): # -> EmailUnconfirmedError | FileMigrateError | FilePartMissingError | FloodPremiumWaitError | FloodTestPhoneWaitError | FloodWaitError | InterdcCallErrorError | InterdcCallRichErrorError | NetworkMigrateError | PasswordTooFreshError | PhoneMigrateError | PreviousChatImportActiveWaitMinError | SessionTooFreshError | SlowModeWaitError | StatsMigrateError | TakeoutInitDelayError | TwoFaConfirmWaitError | UserMigrateError | AuthKeyError | BadRequestError | FloodError | ForbiddenError | InvalidDCError | NotFoundError | ServerError | TimedOutError | UnauthorizedError | RPCError:
    """
    Converts a Telegram's RPC Error to a Python error.

    :param rpc_error: the RpcError instance.
    :param request: the request that caused this error.
    :return: the RPCError as a Python exception that represents this error.
    """
    ...

