"""
This type stub file was generated by pyright.
"""

from .abstract import Session
from .memory import MemorySession

_STRUCT_PREFORMAT = ...
CURRENT_VERSION = ...
class StringSession(MemorySession):
    """
    This session file can be easily saved and loaded as a string. According
    to the initial design, it contains only the data that is necessary for
    successful connection and authentication, so takeout ID is not stored.

    It is thought to be used where you don't want to create any on-disk
    files but would still like to be able to save and load existing sessions
    by other means.

    You can use custom `encode` and `decode` functions, if present:

    * `encode` definition must be ``def encode(value: bytes) -> str:``.
    * `decode` definition must be ``def decode(value: str) -> bytes:``.
    """
    def __init__(self, string: str = ...) -> None:
        ...
    
    @staticmethod
    def encode(x: bytes) -> str:
        ...
    
    @staticmethod
    def decode(x: str) -> bytes:
        ...
    
    def save(self: Session): # -> str:
        ...
    


