"""
This type stub file was generated by pyright.
"""

"""
This module holds several utilities regarding RSA and server fingerprints.
"""
_server_keys = ...
def get_byte_array(integer): # -> bytes:
    """Return the variable length bytes corresponding to the given int"""
    ...

def add_key(pub, *, old): # -> None:
    """Adds a new public key to be used when encrypting new data is needed"""
    ...

def encrypt(fingerprint, data, *, use_old=...): # -> bytes | None:
    """
    Encrypts the given data known the fingerprint to be used
    in the way Telegram requires us to do so (sha1(data) + data + padding)

    :param fingerprint: the fingerprint of the RSA key.
    :param data: the data to be encrypted.
    :param use_old: whether old keys should be used.
    :return:
        the cipher text, or None if no key matching this fingerprint is found.
    """
    ...

