"""
This type stub file was generated by pyright.
"""

from ...tl.tlobject import TLObject
from typing import Optional
from datetime import datetime

"""File generated by TLObjects' generator. All changes will be ERASED"""
class EligibleToJoin(TLObject):
    CONSTRUCTOR_ID = ...
    SUBCLASS_OF_ID = ...
    def __init__(self, terms_url: str, monthly_sent_sms: int) -> None:
        """
        Constructor for smsjobs.EligibilityToJoin: Instance of EligibleToJoin.
        """
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    
    @classmethod
    def from_reader(cls, reader): # -> Self:
        ...
    


class Status(TLObject):
    CONSTRUCTOR_ID = ...
    SUBCLASS_OF_ID = ...
    def __init__(self, recent_sent: int, recent_since: Optional[datetime], recent_remains: int, total_sent: int, total_since: Optional[datetime], terms_url: str, allow_international: Optional[bool] = ..., last_gift_slug: Optional[str] = ...) -> None:
        """
        Constructor for smsjobs.Status: Instance of Status.
        """
        ...
    
    def to_dict(self): # -> dict[str, Any]:
        ...
    
    @classmethod
    def from_reader(cls, reader): # -> Self:
        ...
    


