"""
This type stub file was generated by pyright.
"""

from ...tl.tlobject import TLObject

"""File generated by TLObjects' generator. All changes will be ERASED"""
class SuggestedShortName(TLObject):
    CONSTRUCTOR_ID = ...
    SUBCLASS_OF_ID = ...
    def __init__(self, short_name: str) -> None:
        """
        Constructor for stickers.SuggestedShortName: Instance of SuggestedShortName.
        """
        ...
    
    def to_dict(self): # -> dict[str, str]:
        ...
    
    @classmethod
    def from_reader(cls, reader): # -> Self:
        ...
    


